### ISSUE TITLE
Connect the ultrasonic sensors to the Arduino.

### ISSUE THREAD

**Issue by NearlyEnjoyable** [boldizsarf/morgo-robot#1]
Hello,
I see you have a really nice hardware setup, but I don't know if it's even connected to the Arduino. This seems like a lot of wasted potential.
In the [Todo list](https://github.com/boldizsarf/morgo-robot#todo-list) you currently have these two points after another:

> - Connect the ultrasonic sensors to the Arduino
> 
> - Write the smart obstacle avoidance code

Now the later one depends on the first one and it is also a core element of the robot itself and the progression of the project.

When we can see the change?

**Comment by boldizsarf** [comment]
I will do it in a few days or weeks Sir
